# Generated by Django 3.2.8 on 2021-12-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
