# Generated by Django 3.2.8 on 2021-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_customer_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
