# Generated by Django 3.2.8 on 2022-01-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_auto_20220101_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='optionOneOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='optionTwoOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='optionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spicy', models.CharField(blank=True, choices=[('regular', 'Regular'), ('mild', 'Mild'), ('hot', 'Hot'), ('blend_hot', 'Blend Hot'), ('spicy', 'Spicy')], max_length=50, null=True)),
                ('foodChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.optiononeoptions')),
                ('orderItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='optionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spicy', models.CharField(blank=True, choices=[('regular', 'Regular'), ('mild', 'Mild'), ('hot', 'Hot'), ('blend_hot', 'Blend Hot'), ('spicy', 'Spicy')], max_length=50, null=True)),
                ('foodChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.optiononeoptions')),
                ('orderItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.orderitem')),
            ],
        ),
    ]
