# Generated by Django 3.2.8 on 2022-01-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_auto_20220122_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='option',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
