# Generated by Django 3.2.8 on 2022-02-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_alter_meals_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontwo',
            name='foodChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.optiontwooptions'),
        ),
    ]
