# Generated by Django 3.2.8 on 2022-02-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_alter_optiontwo_foodchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='isTodaySpecial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
