# Generated by Django 3.2.8 on 2021-12-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('totalNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phNo', models.IntegerField()),
                ('resDate', models.DateField()),
                ('resTime', models.TimeField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
            },
        ),
    ]
