# Generated by Django 3.2.8 on 2021-12-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='phNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='resDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='resTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='totalNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
